### ISSUE TITLE
Workflow workflows/ansible-lint.yml uses deprecated ansible/ansible-lint-action@main  

### ISSUE THREAD

**Issue by yurnov** [ansible-network/github_actions#168]
The https://github.com/ansible/ansible-lint-action is unmaintained and is used here:

```
name: ansible-lint
on:
  workflow_call:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ansible-network/github_actions/.github/actions/checkout_dependency@main
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
```

Suggested to be replaced by https://github.com/marketplace/actions/run-ansible-lint
